/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: victory_mirosya (https://sketchfab.com/victory_mirosya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/horse-6b16309d6dfc4ed1978e1748ebcf4530
Title: лошадь horse
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import scene from '../assets/3d/Horse.glb'

const Horse= ({currentAnimation,...props}) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group)
  
  useEffect(()=>{
  Object.values(actions).forEach((action)=>action.stop());
  
  if(actions[currentAnimation]){
    actions[currentAnimation].play();
  }
  },[actions,currentAnimation])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="metarig_49"
                position={[1.023, -2.842, 0]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={[2.42, 2.42, 2.727]}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials['Material.005']}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <group name="Plane_48" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Horse;

